сделал первое задание в рамка проекта
Bakivh/admin-panel-makeup pull request #1
Opened 2022-01-09 19:35 UTC by Bakivh

2022-01-19 23:19 UTC, Muslik requested changes

2022-01-19 23:19 UTC, Muslik commented on style.css
> +	flex-basis: 32px;
Высота в макете больше.

2022-01-19 23:19 UTC, Muslik commented on index.html
> +        <div class="filters__filter-item filters__filter-item_filter1"></div> <!-- названия фильтров потом переименуем -->
Модификатор не может называться _filter1, _filter2.
Модификатор обычно отвечает на вопрос: "Какой?" _disabled, _active,
Или обозначает какой нибудь параметр: _color_primary, _theme_island

2022-01-19 23:19 UTC, Muslik commented on index.html
> +        <div class="filters__filter-item filters__filter-item_filter2"></div>
Как вариант - Я бы тут объединил первые два блока в один. Допустим блок search. Блоку filters бы задал justicy-content: space-between. И тогда будет два блока. Маленький блок справа и большой блок с двумя блоками поменьше слева.

2022-01-19 23:19 UTC, Muslik commented on index.html
> +      <div class=data-table>
nit: Таблица это всегда про данные. Слово data как по мне тут лишнее

2022-01-19 23:19 UTC, Muslik commented on style.css
> +	height: 100%;
Просьба корректно форматировать документ перед пушем

2022-01-19 23:19 UTC, Muslik commented on style.css
> +	margin: 32px 0px 32px 0px;
margin: 32px 0;

2022-01-19 23:19 UTC, Muslik commented on style.css
> +	margin: 32px 0px 32px 0px;
Плюс у блока по БЭМ не должно быть отступов. Они должны быть у элементов.
Чтобы это правило не нарушать, можно обернуть всю страницу в div class="page"

И тогда у header будет два класса. 
<div class="header page__header"></div> В таком случае мы можем основные стили задать блоку .header, а его отступы (margin) указать в классе page__header.
И получается что header является блоком сам по себе, но в контексте данной страницы он является еще и элементом

2022-01-22 15:23 UTC, Bakivh commented on style.css
> +	flex-basis: 32px;
fixed

2022-01-22 15:47 UTC, Bakivh commented on index.html
> +        <div class="filters__filter-item filters__filter-item_filter2"></div>
переделал

2022-01-22 15:47 UTC, Bakivh commented on index.html
> +        <div class="filters__filter-item filters__filter-item_filter1"></div> <!-- названия фильтров потом переименуем -->
переделал структуру

2022-01-22 15:49 UTC, Bakivh commented on style.css
> +	height: 100%;
я просто специально делал логические разделения в разных "блоках" параметров. Мне кажется так нагляднее читать код. Это неправильно?

2022-01-22 15:55 UTC, Bakivh commented on style.css
> +	margin: 32px 0px 32px 0px;
переделал )

2022-01-22 16:42 UTC, Muslik approved these changes

2022-01-22 16:42 UTC, Muslik commented on index.html
> +<html>
Следующую работу без корректного форматирования не приму

2022-01-22 16:42 UTC, Muslik commented on style.css
> +	height: 100%;
Я не про разделение. Отступ - 2 пробела должен быть

2022-01-22 18:17 UTC, Bakivh commented on index.html
> +<html>
Ок, хорошо. prettier установил

2022-01-22 18:17 UTC, merged