добавил npm. добавил prettier в pre-commit на все файлы
Bakivh/admin-panel-makeup pull request #2
Opened 2022-01-22 18:14 UTC by Bakivh

2022-01-24 15:06 UTC, Muslik requested changes
Скрипт запускается, все отлично. Только есть проблема. Я меняю файл, git add, git commit и prettier прогоняет все файлы, но придется снова делать git add, git commit чтобы файлы добавились отформатированные.

2022-01-25 13:46 UTC, Bakivh commented
> Скрипт запускается, все отлично. Только есть проблема. Я меняю файл, git add, git commit и prettier прогоняет все файлы, но придется снова делать git add, git commit чтобы файлы добавились отформатированные.

исправил. Теперь перед коммитом запускается git add

2022-01-25 17:19 UTC, Muslik requested changes

2022-01-25 17:19 UTC, Muslik commented on package.json
> +    "gitadd"
Неа, так не пойдет ))) 
Представим такую ситуацию. Я изменил 20 файлов, но закоммитить хочу только index.html

git add index.html
git commit -m "Finished"
// Вот тут твой скрипт закоммитит вообще все файлы, даже которые я не хочу коммитить
:)

Посмотри в сторону husky + lint-staged

2022-01-25 20:37 UTC, Bakivh commented on package.json
> +    "gitadd"
добавил husky + lint-staged. Вроде теперь все ок. Предлагаю `по этому дз на одном из уроков.
Я не очень понял - получается нам тут утилита pre-commit не нужна, т.к. за нее все husky делает?

2022-01-26 00:05 UTC, Muslik requested changes
https://asciinema.org/a/tH5n76cBKMPI6F4loGNdoSFtB - для index.html prettier не работает

2022-01-26 06:18 UTC, Bakivh commented
> https://asciinema.org/a/tH5n76cBKMPI6F4loGNdoSFtB - для index.html prettier не работает

Да, извиняюсь, пропустил что нет в списке. пофиксил

2022-01-29 16:14 UTC, Muslik approved these changes

2022-01-29 18:18 UTC, merged