сделал инпуты в рамках дз3
Bakivh/admin-panel-makeup pull request #3
Opened 2022-01-29 22:11 UTC by Bakivh

2022-01-29 22:18 UTC, Bakivh commented
задеплоил https://bakivh.github.io/admin-panel-makeup/ui-kit/

2022-02-01 20:07 UTC, Muslik requested changes
Нужны доработки

2022-02-01 20:07 UTC, Muslik commented on ui-kit/index.html
> +            <img class="input-block__button" src="../icons/x-medium.svg" />
Это должны быть кнопка.

2022-02-01 20:07 UTC, Muslik commented on ui-kit/index.html
> +              placeholder="06.12.2021"
Это value.

2022-02-01 20:07 UTC, Muslik commented on ui-kit/index.html
> +              type="datetime"
datetime уже не используется. https://developer.mozilla.org/ru/docs/Web/HTML/Element/Input/datetime

2022-02-01 20:07 UTC, Muslik commented on ui-kit/input.css
> +  margin: 8px 0px;
margin сверху не нужен

2022-02-01 20:07 UTC, Muslik commented on ui-kit/input.css
> +  padding: 8px 0px;
В чем смысл этих паддингов?

2022-02-01 20:07 UTC, Muslik commented on ui-kit/input.css
> +.input-space {
Иконки не должны быть фиолетовыми

2022-02-01 20:07 UTC, Muslik commented on ui-kit/index.html
> +              class="input-block__input-text input-block__input-text_disabled"
Этот input должен быть disabled

2022-02-01 20:07 UTC, Muslik commented on ui-kit/index.html
> +              class="input-block__input-text input-block__input-text_disabled"
Цвет placeholder-а не как на макете

2022-02-05 12:10 UTC, Bakivh commented on ui-kit/index.html
> +              type="datetime"
fixed

2022-02-05 12:13 UTC, Bakivh commented on ui-kit/input.css
> +  margin: 8px 0px;
поменял, сделал margin у input

2022-02-05 12:14 UTC, Bakivh commented on ui-kit/input.css
> +  padding: 8px 0px;
остался с прошлого кода, убрал

2022-02-05 12:40 UTC, Bakivh commented on ui-kit/index.html
> +              placeholder="06.12.2021"
ok

2022-02-05 12:55 UTC, Bakivh commented on ui-kit/index.html
> +            <img class="input-block__button" src="../icons/x-medium.svg" />
обернул кнопкой

2022-02-05 13:20 UTC, Bakivh commented on ui-kit/input.css
> +.input-space {
исправил

2022-02-05 13:34 UTC, Bakivh commented on ui-kit/index.html
> +              class="input-block__input-text input-block__input-text_disabled"
> Этот input должен быть disabled

исправил

> Цвет placeholder-а не как на макете

Да, извиняюсь, проглядел

2022-02-05 17:29 UTC, Muslik requested changes
Пару замечаний

2022-02-05 17:29 UTC, Muslik commented on ui-kit/input.css
> +}
https://ibb.co/H2H8vCM. 
outline при фокусе отключать не нужно. Если его включить то outline получает вот этот небольшой кусочек. А должен весь блок

2022-02-05 17:29 UTC, Muslik commented on ui-kit/index.html
> +              onfocus="(this.type='date')"
Это что такое? :) 

Везде сделайте type='text'. И проблема будет решена. Только не забывайте что у второго и третьего элемента должен быть placeholder

2022-02-05 17:29 UTC, Muslik commented on ui-kit/index.html
> +            <button class="input-block__button">
Это должно быть просто иконкой

2022-02-05 21:36 UTC, Bakivh commented on ui-kit/index.html
> +              onfocus="(this.type='date')"
ок. изменил. Я почему то из чата понял что тип должен быть date

2022-02-05 21:36 UTC, Bakivh commented on ui-kit/input.css
> +}
сделал через focus-within

2022-02-05 21:39 UTC, Bakivh commented on ui-kit/index.html
> +            <button class="input-block__button">
изменил

2022-02-08 17:43 UTC, Muslik approved these changes
Ok

2022-02-08 17:59 UTC, merged