Makeup button
Bakivh/admin-panel-makeup pull request #6
Opened 2022-02-19 19:28 UTC by Bakivh

ссылка https://bakivh.github.io/admin-panel-makeup/ui-kit

тут я как говорили сделал ветку button (дз6) от предыдущей дз5 , которую сегодня отдал на проверку.
Я понял в чем недостаток - получается не очень удобно что в сравнении тебе будет подсвечиваться изменения и предыдущего дз

2022-02-20 05:58 UTC, Muslik requested changes
https://youtu.be/WieOA09XrBo

2022-02-20 06:11 UTC, Muslik commented
Чего то я на качество не глянул. Если будет непонятно что на видео, текстом опишу

2022-02-20 15:34 UTC, Bakivh commented
качество малех размытое, но в целом все понятно.
Все исправил по комментариям, вроде как теперь все хорошо.
Только по поводу ховеров не совсем понял, если их убрать кнопка же не будет "нажиматься". 
Сергей вроде на лекции говорил что как раз в этом случае если в дизайне и не было то надо исходить из здравого смысла (из "насмотренности" как он сказал :) )

2022-02-22 22:11 UTC, Muslik approved these changes
Исправьте мелкие замечание. В целом все ок

2022-02-22 22:11 UTC, Muslik commented on ui-kit/index.html
> +              fill="#FFFFFF"
Вот это должно переехать в css и зависеть от выбранной темы

2022-02-22 22:11 UTC, Muslik commented on ui-kit/button.css
> +.button > .button__text {
Нет смысла тут использовать еще и .button
Просто .button__text

2022-02-22 22:11 UTC, Muslik commented on ui-kit/button.css
> +}
Тоже самое. Просто .button__icon

2022-02-22 22:11 UTC, Muslik commented on ui-kit/button.css
> +  font-weight: 400;
Вот это можно перенести в сам button__text.

2022-02-23 10:11 UTC, Bakivh commented on ui-kit/index.html
> +              fill="#FFFFFF"
исправил

2022-02-23 10:12 UTC, Bakivh commented on ui-kit/button.css
> +.button > .button__text {
done

2022-02-23 10:12 UTC, Bakivh commented on ui-kit/button.css
> +}
done

2022-02-23 10:13 UTC, Bakivh commented on ui-kit/button.css
> +  font-weight: 400;
оставил пока так , ведь вдруг толщина будет зависеть от темы

2022-02-23 10:18 UTC, merged