Makeup dropdown
Bakivh/admin-panel-makeup pull request #7
Opened 2022-02-20 19:15 UTC by Bakivh

дз7 https://bakivh.github.io/admin-panel-makeup/ui-kit/

2022-02-20 19:39 UTC, Bakivh commented
как то странно, gitgub pages не подтягивает свежие стили, а подтягивает из другой ветки :((

2022-02-20 20:25 UTC, Bakivh commented
о, а теперь все ок.

2022-02-22 22:23 UTC, Muslik requested changes

2022-02-22 22:23 UTC, Muslik commented on ui-kit/index.html
> +          <label class="checkbox-input">
Вы уже верстали свой чекбокс. Почему бы не использовать его тут

2022-02-22 22:23 UTC, Muslik commented on ui-kit/index.html
> +          <label class="checkbox-input">
Отступ сверху который вы назначили тут должен быть padding-ом блока .dropdown

2022-02-22 22:23 UTC, Muslik commented on ui-kit/index.html
> +          <label class="checkbox-input">
В figma https://ibb.co/6XghP0V этот блок тянется на всю ширину и у него есть внутренние отступы и они прилегают друг к другу. В вашем случае я сейчас могу кликнуть на пустое место между блоками и ничего не произойдет

2022-02-22 22:23 UTC, Muslik commented on ui-kit/index.html
> +            <input type="checkbox" />
Это должны быть radio

2022-02-22 22:23 UTC, Muslik commented on ui-kit/index.html
> +          <button class="button button_theme-light button-dropdown">
КЛасса button-dropdown быть не должно. Скорее dropdown__button. Но и это будет неправильно.
У вас у кнопки появился новый стиль - растянутая на всю ширину. И это будет использоваться где то еще. И все что меняется что width: 100% и выравнивание по центру. Поэтому стоит апгрейднуть вашу кнопку добавив ей новый... модификатор

2022-02-22 22:23 UTC, Muslik commented on ui-kit/index.html
> +          <button class="button button_theme-light button-dropdown">
Цвет не как на макете

2022-02-22 22:23 UTC, Muslik commented on ui-kit/index.html
> +          <div class="input-block input-block_dropdown">
dropdown не может быть модификатором

2022-02-22 22:23 UTC, Muslik commented on ui-kit/index.html
> +          <div class="input-block input-block_dropdown">
И его отступ сверху должен быть padding-ом всего блока. Это касается всех ваших сверстанных блоков

2022-02-22 22:23 UTC, Muslik commented on ui-kit/index.html
> +            class="button button_theme-light button-dropdown button_highlighted"
Зачем тут непонятный button_highlighted если у вас есть отдельная тема для такого стиля

2022-02-22 22:23 UTC, Muslik commented on ui-kit/ui-kit.css
> +  padding: 48px 48px 48px 48px;
padding: 48px

2022-02-23 10:47 UTC, Bakivh commented on ui-kit/ui-kit.css
> +  padding: 48px 48px 48px 48px;
done

2022-02-23 10:52 UTC, Bakivh commented on ui-kit/index.html
> +            class="button button_theme-light button-dropdown button_highlighted"
исправил

2022-02-23 10:54 UTC, Bakivh commented on ui-kit/index.html
> +          <button class="button button_theme-light button-dropdown">
исправил

2022-02-23 11:00 UTC, Bakivh commented on ui-kit/index.html
> +          <button class="button button_theme-light button-dropdown">
исправил

2022-02-23 12:04 UTC, Bakivh commented on ui-kit/index.html
> +          <label class="checkbox-input">
1. так я вроде и использую тот чекбокс что делал ранее (оттуда скопипастил)
2. переделал. Я правильно понимаю что логика такая - делаем паддинг 16px 0px 0 0px. Т.е. везде отступ сверху делаем а винзу нет, а элементы внутри делаем со сдвигом вниз 16px. или как
3. Переделал margin на padding, теперь кликабельно пустое место

2022-02-23 15:12 UTC, Bakivh commented on ui-kit/index.html
> +          <div class="input-block input-block_dropdown">
вроде исправил , если я правильно понял )

2022-02-23 15:50 UTC, Bakivh commented on ui-kit/index.html
> +            <input type="checkbox" />
переделал

2022-02-23 15:56 UTC, Bakivh commented
поправил

2022-03-04 06:42 UTC, Muslik approved these changes

2022-03-08 16:57 UTC, merged